# Tasca S9.01. Creació de funcions, estructures de dades i bucles

Un client de l'empresa en la qual treballes demana una llista de programes molt senzills, però que li facilitarien molts processos.

Se’t demanarà que programis varies funcions. Per a fer l’entrega, hauràs d’entregar tant el codi de la funció:

def funcioexemple(variable1, variable2):

resultat = variable1 + variable2 # sumem les dues variables

return resultat

Com la seva execució per demostrar que funciona correctament, ensenyant-ne l’output:

funcioexemple(3, 8)

Intenta que tot el codi que generis sigui el més reproduïble possible.

In [126]:
import re
from collections import Counter
import pandas as pd
import random
import string
import numpy as np
import pyperclip

# Nivell 1


## 1. Calculadora de l'índex de massa corporal

Escriu una funció que calculi l'IMC ingressat per l'usuari/ària, és a dir, qui ho executi haurà d'ingressar aquestes dades. Pots obtenir més informació del seu càlcul en: 🔗 Índice de masa corporal IMC que es y como se calcula.

La funció ha de classificar el resultat en les seves respectives categories.

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduïdes per l’usuari/a no estan en el format adequat o no pren valors raonables.

In [75]:
def demanar_pes_i_altura():
    """
    Demana a l'usuari el pes (kg) i l'alçada (cm), validant que siguin valors numèrics
    i dins d'un rang raonable.
    
    Retorna:
        tuple: (pes_en_kg, altura_en_cm)
    """
    while True:
        try:
            pes = int(input("Introdueix el pes en Kg:"))
            altura = int(input("Introdueix l'alçada en cm:"))
            if not (20 < pes < 600):
                print("Pes fora de rang(20-600kg), torna-ho a intentar")
                continue
            if not (80 < altura < 250):
                print("Alçada fora de rang (80-250), torna-ho a intentar")
                continue

            return pes, altura
        except ValueError:
            print("Dades incorrectes, torna-ho a introduir-les:")

In [76]:
def calcular_imc(pes, altura_cm):
    """
    Calcula l'Índex de Massa Corporal (IMC) a partir del pes (kg)
    i l'alçada (cm).

    Fórmula:
        IMC = pes / (altura_en_metres ** 2)

    Retorna:
        float: valor de l'IMC arrodonit a 1 decimal.
    """
    altura_m = altura_cm / 100
    imc = pes / (altura_m ** 2)
    return round(imc, 1)

In [77]:
def classificar_imc(imc_valor):
    """
    Classifica un valor d'IMC segons els rangs estàndard de l'OMS.

    Categories:
        - < 16       → massa baix (desnutrició severa)
        - 16–18.5    → baix (desnutrició moderada/lleu)
        - 18.5–24.9  → normal
        - 25–29.9    → sobrepès
        - ≥ 30       → obesitat

    Retorna:
        str: categoria corresponent.
    """
    if imc_valor < 16:
        return "massa baix"
    if 16 <= imc_valor < 18.5:
        return "baix"
    if 18.5 <= imc_valor <= 24.9:
        return "normal"
    if 25 <= imc_valor <= 29.9:
        return "sobrepès"
    return "obesitat"

In [78]:
def imc():
    """
    Flux complet del càlcul d'IMC:
    - demana pes i alçada a l'usuari
    - calcula l'IMC
    - classifica el resultat
    - retorna un missatge final amb tota la informació

    Retorna:
        str: missatge amb el valor d'IMC i la seva categoria.
    """
    pes, altura = demanar_pes_i_altura()
    valor = calcular_imc(pes, altura)
    categoria = classificar_imc(valor)
    return f"L'índex de massa corporal (IMC) és {valor} i es considera {categoria}."

In [79]:
# Execució de la funció IMC
imc()

"L'índex de massa corporal (IMC) és 27.7 i es considera sobrepès."

## 2. Convertidor de temperatures

Existeixen diverses unitats de temperatura utilitzades en diferents contextos i regions. Les més comunes són Celsius (°C), Fahrenheit (°F) i Kelvin (K). També existeixen altres unitats com Rankine (°Ra) i Réaumur (°Re).

Selecciona almenys 2 conversors, de tal manera que en introduir una temperatura retorni, com a mínim, dues conversions, de manera que es puguin guardar (recorda que un print() no es pot guardar mai).

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduides per l’usuari/a no estan en el format adequat.

(EXTRA): Pensa una manera d’emmagatzemar totes les possibles conversions en un sol objecte (Llista? Diccionari? DataFrame?) en comptes d’escriure molts if else en funció de la temperatura d’origen i la temperatura de destí.

In [80]:
conversions = {
    ("C", "F"): lambda x: x * 1.8 + 32,
    ("C", "K"): lambda x: x + 273.15,
    ("C", "R"): lambda x: (x + 273.15) * 1.8,

    ("F", "C"): lambda x: (x - 32) / 1.8,
    ("F", "K"): lambda x: (x + 459.67) / 1.8,
    ("F", "R"): lambda x: x + 459.67,

    ("K", "C"): lambda x: x - 273.15,
    ("K", "F"): lambda x: x * 1.8 - 459.67,
    ("K", "R"): lambda x: x * 1.8,

    ("R", "C"): lambda x: (x / 1.8) - 273.15,
    ("R", "F"): lambda x: x - 459.67,
    ("R", "K"): lambda x: x / 1.8,
}

In [81]:
def demanar_dades_temperatura():
    """
    Demana a l'usuari una temperatura i tres unitats:
    - unitat d'origen
    - dues unitats de destí

    Valida:
        - que la temperatura sigui numèrica
        - que les unitats siguin C, F, K o R
        - que les unitats de destí no siguin iguals a l'origen
        - que les dues unitats de destí no siguin iguals entre elles

    Retorna:
        tuple: (temperatura, origen, desti1, desti2)
    """
    unitats_valides = {"C", "F", "K", "R"}

    while True:
        # Temperatura
        try:
            temperatura = float(input("Introdueix la temperatura: "))
        except ValueError:
            print("⚠️ La temperatura ha de ser un número.")
            continue

        # Unitats
        origen = input("Unitat d'origen (C/F/K/R): ").upper()
        desti1 = input("Primera unitat de destí (C/F/K/R): ").upper()
        desti2 = input("Segona unitat de destí (C/F/K/R): ").upper()

        # Validació d’unitats
        if not {origen, desti1, desti2}.issubset(unitats_valides):
            print("Unitats incorrectes. Només s'accepten C, F, K o R.")
            continue

        # Evitar repeticions de les unitats
        if origen == desti1 or origen == desti2:
            print("Les unitats de destí han de ser diferents de l'origen.")
            continue

        if desti1 == desti2:
            print("Les dues unitats de destí han de ser diferents entre elles.")
            continue

        return temperatura, origen, desti1, desti2

In [82]:
def convertir(temperatura, origen, desti1, desti2, conversions):
    """
    Converteix una temperatura des d'una unitat d'origen cap a dues unitats de destí,
    utilitzant el diccionari de conversions proporcionat.

    Paràmetres:
        temperatura (float): valor numèric de la temperatura.
        origen (str): unitat d'origen ('C', 'F', 'K', 'R').
        desti1 (str): primera unitat de destí.
        desti2 (str): segona unitat de destí.
        conversions (dict): diccionari amb tuples (origen, destí) com a claus
                            i funcions lambda com a valors.

    Retorna:
        tuple: (resultat1, resultat2) amb les dues conversions.
    """
    try:
        resultat1 = conversions[(origen, desti1)](temperatura)
        resultat2 = conversions[(origen, desti2)](temperatura)
        return resultat1, resultat2

    except KeyError:
        raise ValueError("Conversió no definida en el diccionari.")

In [83]:
def convertidor(conversions):
    """
    Flux complet del convertidor de temperatures:
    - demana la temperatura i les unitats
    - aplica les conversions corresponents
    - retorna un missatge final amb els dos resultats

    Retorna:
        str: missatge amb les dues conversions realitzades.
    """
    temperatura, origen, desti1, desti2 = demanar_dades_temperatura()
    resultat1, resultat2 = convertir(temperatura, origen, desti1, desti2, conversions)

    return (f"{temperatura}°{origen} equival a "
            f"{round(resultat1, 2)}°{desti1} i "
            f"{round(resultat2, 2)}°{desti2}.")

In [84]:
# Execució del convertidor de temperatures
convertidor(conversions)

'30.0°C equival a 86.0°F i 303.15°K.'

## 3. Comptador de paraules d'un text.

Escriu una funció que donat un text, mostri les vegades que apareix cada paraula. Intenta que es gestionin totes les casuístiques possibles que facin que el programa no funcioni correctament.

(EXTRA): Quina és la llargada mitjana de les paraules del text que has escrit? “Hola com va?” hauria de retornar (4+3+2) / 3 = 3

In [ ]:
def netejar_text_regex(text):
    """
    Rep un text i retorna una llista de paraules netes:
    - tot en minúscules
    - sense signes de puntuació
    - només seqüències de caràcters alfanumèrics

    Retorna:
        list: llista de paraules netes.
    """
    return re.findall(r"\b\w+\b", text.lower())

In [86]:
def comptar_paraules_regex(text):
    """
    Rep un text, l'envia a netejar i retorna un diccionari
    {paraula: recompte} utilitzant Counter.

    Retorna:
        dict: paraula → freqüència
    """
    paraules = netejar_text_regex(text)
    return dict(Counter(paraules))

In [87]:
def llargada_mitjana_regex(text):
    """
    Calcula la llargada mitjana de les paraules del text.

    Retorna:
        float: mitjana de llargada, o 0 si no hi ha paraules.
    """
    paraules = netejar_text_regex(text)
    if not paraules:
        return 0
    llargades = [len(p) for p in paraules]
    return sum(llargades) / len(llargades)

In [88]:
def comptador_regex(text):
    """
    Orquestra el procés complet:
    - neteja el text
    - compta paraules
    - calcula la llargada mitjana

    Retorna:
        str: missatge final amb resultats.
    """
    comptatge = comptar_paraules_regex(text)
    mitjana = llargada_mitjana_regex(text)

    return (f"Recompte de paraules: {comptatge}\n"
            f"Llargada mitjana: {round(mitjana, 2)}")

In [89]:
# Execució amb print del comptador de paraules
print(comptador_regex("Hola, com va?, va bé si vinc dissabte? Com et va?"))

Recompte de paraules: {'hola': 1, 'com': 2, 'va': 3, 'bé': 1, 'si': 1, 'vinc': 1, 'dissabte': 1, 'et': 1}
Llargada mitjana: 3.09

## 4. Diccionari invers (amb possibilitat de duplicats)

Resulta que el client té una enquesta molt antiga que s'emmagatzema en un diccionari i els resultats els necessita al revés, és a dir, intercanviant les claus i els valors. Els valors i claus en el diccionari original són únics; si aquest no és el cas, la funció hauria d'imprimir un missatge d'advertiment, juntament amb una llista amb els valors associats a la clau repetida.

In [90]:
def diccionari_invers(diccionari):
    """
    Rep un diccionari i en retorna un de nou amb claus i valors intercanviats.
    
    Si algun valor del diccionari original es repeteix, es guarda una llista
    amb totes les claus associades a aquell valor i es retorna també un missatge
    d'advertiment indicant quins valors estaven duplicats.

    Retorna:
        tuple: (diccionari_invertit, missatge_advertencia)
    """
    
    invertit = {}
    duplicats = []

    for clau, valor in diccionari.items():
        if valor not in invertit:
            invertit[valor] = [clau]
        else:
            invertit[valor].append(clau)
            if valor not in duplicats:
                duplicats.append(valor)

    if duplicats:
        missatge = f"Atenció: els valors {duplicats} apareixen repetits."
    else:
        missatge = "No s'han trobat valors duplicats."

    return invertit, missatge

In [91]:
# Exemple de diccionari 
dicc_original = {
    "x": "apple",
    "y": "banana",
    "z": "banana",
    "w": "apple",
    "p": "banana"
}

# Execució de la funció
dicc_invertit, missatge = diccionari_invers(dicc_original)

print(dicc_invertit, missatge)

{'apple': ['x', 'w'], 'banana': ['y', 'z', 'p']} Atenció: els valors ['banana', 'apple'] apareixen repetits.

# Nivell 2


## 1. Comptador i endreçador de paraules d'un text.

El client va quedar content amb el comptador de paraules, però ara vol llegir arxius TXT i que calculi la freqüència de cada paraula ordenades dins de les entrades habituals del diccionari segons la lletra amb la qual comencen, és a dir, les claus han d'anar de la A a la Z i dins de la A hem d'anar de la A la Z.

In [92]:
# Reutilització de funcions del Nivell 1 Exercici 3

# Funció per netejar text amb regex
def netejar_text_regex(text):
    return re.findall(r"\b\w+\b", text.lower())

# Funció per comptar paraules amb Counter
def comptar_paraules_regex(text):
    paraules = netejar_text_regex(text)
    return dict(Counter(paraules))

In [93]:
def llegir_txt(path):
    """
    Rep la ruta d'un fitxer TXT i en retorna el contingut com a string.
    """
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

In [94]:
def ordenar_paraules(diccionari):
    """
    Rep un diccionari {paraula: recompte} i el retorna ordenat alfabèticament.
    """
    return dict(sorted(diccionari.items()))

In [95]:
def agrupar_per_inicial(diccionari_ordenat):
    """
    Rep un diccionari {paraula: recompte} ja ordenat alfabèticament
    i el transforma en un diccionari agrupat per la lletra inicial.
    """
    agrupat = {}

    for paraula, freq in diccionari_ordenat.items():
        inicial = paraula[0]

        if inicial not in agrupat:
            agrupat[inicial] = {}

        agrupat[inicial][paraula] = freq

    return agrupat

In [96]:
def comptar_i_ordenar_text(text):
    """
    Orquestra del procés:
    - neteja el text (reutilitzat del Nivell 1 Exercici 3)
    - compta paraules (reutilitzat del Nivell 1 Exercici 3)
    - ordena alfabèticament
    - agrupa per inicial
    """
    recompte = comptar_paraules_regex(text)
    ordenat = ordenar_paraules(recompte)
    agrupat = agrupar_per_inicial(ordenat)
    return agrupat

In [97]:
# Execució final de l'exercici

# 1. Llegim el fitxer
text = llegir_txt("tu me quieres blanca.txt")

# 2. Processem el text
resultat = comptar_i_ordenar_text(text)

# 3. Mostrem el resultat
resultat

{'a': {'a': 3,
  'agua': 1,
  'al': 2,
  'alba': 4,
  'alcobas': 1,
  'alimenta': 1,
  'alma': 1,
  'amarga': 1,
  'azucena': 1},
 'b': {'baco': 1,
  'banquete': 1,
  'bebe': 1,
  'blanca': 3,
  'boca': 1,
  'bosques': 1,
  'buen': 1},
 'c': {'cabañas': 1,
  'carnes': 2,
  'casta': 3,
  'cerrada': 1,
  'con': 4,
  'conservas': 1,
  'copas': 1,
  'corola': 1,
  'corriste': 1,
  'cuando': 2,
  'cubierto': 1,
  'cuerpo': 1,
  'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
  'ellas': 1,
  'en': 4,
  'engaño': 1,
  'enredada': 1,
  'entonces': 1,
  'escarcha': 1,
  'espumas': 1,
  'esqueleto': 1,
  'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
  'hacia': 1,
  'haya': 1,
  'hayas': 1,
  'hermana': 1,
  'hombre': 1,
  'hubiste': 1,
  'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
  'labios': 1,
  'las': 7,
  'lo': 2,
  'los': 4,
  'luna': 1,
  'lévate': 1,
  'límpiate': 1},
 'm': {'mano': 1,
  'manos': 1,
  'margarita': 1,
  'me': 10,
  'mi': 1,
  'mieles': 1,
  'milagros': 1,
  'mojada': 1,
  'montaña': 1,
  'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone': 2,
  'perfume': 1,
  'por': 2,
  'pretendes': 3,
  'preténdeme': 3,
  'puesto': 1,
  'pájaros': 1,
  'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
  'tejidos': 1,
  'tenue': 1,
  'tierra': 1,
  'toca': 1,
  'todas': 2,
  'todavía': 1,
  'tornadas': 1,
  'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5}}

## 2. Conversió de tipus de dades.

El client rep una llista de dades i necessita generar dues llistes, la primera on estaran tots els elements que es van poder convertir en flotants i l'altra on estan els elements que no es van poder convertir. Exemple de la llista que rep el client:

In [105]:
def processar_element(i, floats, no_floats):
    """
    Processa un element i l'afegeix a floats o no_floats.
    """
    try:
        floats.append(float(i))
    except:
        if isinstance(i, (tuple, list, set)):
            for e in i:
                try:
                    floats.append(float(e))
                except:
                    no_floats.append(e)
        else:
            no_floats.append(i)

In [108]:
def convertir_llista(llista):
    """
    Orquestra del procés de conversió:
    - crea les llistes locals
    - processa cada element amb processar_element()
    - retorna el resultat final
    """
    paraules_float = []
    paraules_no_float = []

    for i in llista:
        processar_element(i, paraules_float, paraules_no_float)

    return paraules_float, paraules_no_float

In [152]:
llista_client = [ '1.3', 'one' , '1e10' , 'seven', '3-1/2',
                  ('2',1,1.4,'not-a-number'), [1,2,'3','3.4'] ]

# Execució del exercici
convertir_llista(llista_client)

([1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4],
 ['one', 'seven', '3-1/2', 'not-a-number'])

# Nivell 3


## 1. Generador de Contrasenyes

Explora el funcionament del mòdul random de la llibreria numpy. 🔗 Random module in NumPy

En aquest punt, el client ha detectat un problema amb les contrasenyes que utilitzen els seus treballadors. Asdf1234, dates d’aniversari o similars. Per a solucionar-ho ens ha encarregat una funció de Python que generi contrasenyes més segures. La funció ha de dependre dels següents paràmetres:

longitud (int): Longitud de la contrasenya

majuscules (bool = True): Si hi ha d’aparèixer majúscules

minuscules (bool = True): Si hi ha d’aparèixer minúscules

numeros (bool = True): Si hi ha d’aparèixer números

signes (bool = False): Si hi ha d’aparèixer caràcters especials (,-$? o similars)

Així doncs, si executem la funció de la següent manera:

crear_contrasenya(10, True, True, True, True)

Hauríem d’obtenir un output (que hem de poder guardar) de l’estil:

9Er,5Vn8P$

Assegura’t que es compleixin tots els criteris, i que aquestes contrasenyes siguin realment aleatòries.

(EXTRA) Explora com podríem fer que la funció copiés la contrasenya automàticament al porta papers de l’ordinador (com si l’haguéssim seleccionat i fet ctrl+copy).

In [118]:
def obtenir_categories(maj, min, num, sig):
    """
    Retorna una llista de conjunts de caràcters segons els paràmetres activats.
    Cada element de la llista és un string amb els caràcters disponibles.
    """
    categories = []

    if maj:
        categories.append(string.ascii_uppercase)
    if min:
        categories.append(string.ascii_lowercase)
    if num:
        categories.append(string.digits)
    if sig:
        categories.append(string.punctuation)

    return categories

In [119]:
def validar_parametres(longitud, categories):
    """
    Comprova que la longitud és suficient per incloure
    almenys un caràcter de cada categoria activada.
    """
    if longitud < len(categories):
        raise ValueError("La longitud és massa curta per incloure totes les categories activades.")

In [120]:
def generar_base(categories):
    """
    Genera un caràcter de cada categoria activada.
    categories és una llista de strings, cadascun amb caràcters possibles.
    """
    return [np.random.choice(list(cat)) for cat in categories]

In [153]:
def generar_restants(longitud, base, categories):
    """
    Genera la resta de caràcters fins arribar a la longitud total.
    categories és una llista de strings amb caràcters disponibles.
    """
    resta = longitud - len(base)
    tots = "".join(categories)  

    # Generem 'resta' caràcters aleatoris de tots els disponibles
    return list(np.random.choice(list(tots), size=resta))

In [122]:
def barrejar(contrasenya):
    """
    Rep una llista de caràcters i la barreja aleatòriament.
    Retorna la contrasenya final com un string.
    """
    np.random.shuffle(contrasenya)
    return "".join(contrasenya)

In [128]:
def copiar_portapapers(contrasenya):
    """
    Intenta copiar la contrasenya al porta-retalls.
    Retorna un missatge informatiu segons si ha funcionat o no.
    """
    try:
        pyperclip.copy(contrasenya)
        return f"S'ha creat la nova contrasenya, i ja està llesta per a enganxar"
    except:
        return f"S'ha creat la nova contrasenya, però no s'ha pogut copiar al porta-retalls"

In [129]:
def crear_contrasenya(longitud, maj=True, min=True, num=True, sig=False):
    """
    Genera una contrasenya aleatòria segons els criteris especificats.

    Paràmetres:
        longitud (int): Longitud total de la contrasenya.
        maj (bool, opcional): Incloure majúscules. Per defecte True.
        min (bool, opcional): Incloure minúscules. Per defecte True.
        num (bool, opcional): Incloure números. Per defecte True.
        sig (bool, opcional): Incloure signes de puntuació. Per defecte False.

    Retorna:
        str: Missatge informatiu indicant la contrasenya generada i si s'ha copiat al porta-retalls.
    """

    # 1. Obtenir categories activades
    categories = obtenir_categories(maj, min, num, sig)

    # 2. Validar que la longitud és suficient
    validar_parametres(longitud, categories)

    # 3. Generar la base (1 caràcter per categoria)
    base = generar_base(categories)

    # 4. Generar la resta de caràcters
    restants = generar_restants(longitud, base, categories)

    # 5. Construir la contrasenya completa
    contrasenya = base + restants

    # 6. Barrejar-la
    contrasenya = barrejar(contrasenya)

    # 7. Copiar al porta-retalls i retornar missatge
    return copiar_portapapers(contrasenya)

In [130]:
# Execució de prova del generador de contrasenyes
crear_contrasenya(10, True, True, True, True)

"S'ha creat la nova contrasenya, i ja està llesta per a enganxar"

## 2. Processament de dades simple

Una companya de feina ens ha demanat un favor, aprofitant que sap que estem aprenent a programar. Té un històric de partits de futbol català en un fitxer, on hi ha emmagatzemat els noms dels equips i els resultats. Necessita que processem les dades de manera automàtica, per extreure’n els resultats que necessita.

Utilitza el fitxer "historic_partits.txt"

Necessita un programa que retorni:

El nombre total de gols que ha fet cada equip.

El nom de l’equip més golejador.

El nom de l’equip més golejat

La classificació global (cada victòria: 3 pts, empat 1 pts, derrota 0 pts)

In [131]:
def calcular_gols(partits_df):
    """
    Calcula el total de gols marcats per cada equip.
    
    Retorna:
        gols (DataFrame): Taula amb columnes ["Equip", "Gols"] ordenada descendentment.
        maxim (Series): Fila amb l'equip més golejador i els seus gols.
    """
    gols = (
        partits_df.groupby("Local")["G local"].sum() +
        partits_df.groupby("Visitant")["G visitant"].sum()
    ).sort_values(ascending=False)

    gols = gols.reset_index()
    gols.columns = ["Equip", "Gols"]

    maxim_golejador = gols.iloc[0]   

    return gols, maxim_golejador


def calcular_gols_rebuts(partits_df):
    """
    Calcula el total de gols rebuts per cada equip.
    
    Retorna:
        gols (DataFrame): Taula amb columnes ["Equip", "Gols"] ordenada descendentment.
        maxim (Series): Fila amb l'equip més golejat i els seus gols rebuts.
    """
    gols = (
        partits_df.groupby("Local")["G visitant"].sum() +
        partits_df.groupby("Visitant")["G local"].sum()
    ).sort_values(ascending=False)

    gols = gols.reset_index()
    gols.columns = ["Equip", "Gols"]

    maxim_coladero = gols.iloc[0]   

    return gols, maxim_coladero

In [133]:
def llegir_partits(path):
    """
    Llegeix un fitxer de text amb l'històric de partits.

    Paràmetres:
        path (str): Ruta del fitxer.

    Retorna:
        list[str]: Llista de línies del fitxer sense salts de línia finals.
    """
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    return text.split("\n")


def parsejar_partits(lines):
    """
    Converteix les línies del fitxer en una estructura tabular bàsica.

    Cada línia té el format:
        EquipLocal \t GolsLocal-GolsVisitant \t EquipVisitant
        
    Elimina lineas que no compleixen el criteri    

    Retorna:
        list[list]: Llista de files parsejades amb:
            [Local, G_local, G_visitant, Visitant]
    """
    partits_frame = [l.split("\t") for l in lines]

    # Eliminar línies buides o mal formades
    partits_frame = [fila for fila in partits_frame if len(fila) == 3]

    # Convertir resultat en dos columnes "2-1" → (2, 1)
    for fila in partits_frame:
        gols_local, gols_visitant = fila[1].split("-")
        fila[1] = int(gols_local)
        fila.insert(2, int(gols_visitant))

    return partits_frame


def crear_dataframe(partits_frame):
    """
    Converteix la llista de partits parsejats en un DataFrame.

    Columnes:
        - Local
        - G local
        - G visitant
        - Visitant

    Retorna:
        DataFrame: Taula amb tots els partits.
    """
    return pd.DataFrame(
        partits_frame,
        columns=["Local", "G local", "G visitant", "Visitant"]
    )

In [134]:
def carregar_partits(path):
    """
    Carrega un fitxer de partits i el converteix en un DataFrame llest per analitzar.

    Pipeline:
        1. Llegeix el fitxer de text.
        2. Parseja cada línia en camps estructurats.
        3. Construeix un DataFrame amb les columnes:
           ["Local", "G local", "G visitant", "Visitant"]

    Paràmetres:
        path (str): Ruta del fitxer "historic_partits.txt".

    Retorna:
        DataFrame: Taula amb tots els partits processats.
    """
    lines = llegir_partits(path)
    frame = parsejar_partits(lines)
    df = crear_dataframe(frame)
    return df

In [135]:
def guanyador(fila):
    """
    Determina el resultat d'un partit.

    Paràmetres:
        fila (Series): Fila del DataFrame amb les columnes:
                       "Local", "G local", "G visitant", "Visitant"

    Retorna:
        str: Nom de l'equip guanyador o "empat" si no hi ha vencedor.
    """
    if fila["G local"] > fila["G visitant"]:
        return fila["Local"]
    elif fila["G local"] < fila["G visitant"]:
        return fila["Visitant"]
    else:
        return "empat"


def calcular_classificacio(partits_df):
    """
    Calcula la classificació de la lliga segons:
        - victòria: 3 punts
        - empat: 1 punt
        - derrota: 0 punts

    Paràmetres:
        partits_df (DataFrame): Taula amb tots els partits.

    Retorna:
        DataFrame: Classificació amb columnes ["Equip", "Punts"],
                   ordenada descendentment.
    """
    # Afegim columna amb el guanyador de cada partit
    partits_df["Guanyador"] = partits_df.apply(guanyador, axis=1)

    classificacio = {}

    for _, fila in partits_df.iterrows():
        local = fila["Local"]
        visitant = fila["Visitant"]
        vencedor = fila["Guanyador"]

        # Inicialitzar equips si no hi són
        if local not in classificacio:
            classificacio[local] = 0
        if visitant not in classificacio:
            classificacio[visitant] = 0

        # Assignació de punts
        if vencedor == local:
            classificacio[local] += 3
        elif vencedor == visitant:
            classificacio[visitant] += 3
        else:
            classificacio[local] += 1
            classificacio[visitant] += 1

    classificacio_df = (
        pd.Series(classificacio)
        .reset_index()
        .rename(columns={"index": "Equip", 0: "Punts"})
        .sort_values("Punts", ascending=False)
        .reset_index(drop=True)
    )

    return classificacio_df

In [137]:
def calcular_estadistiques(partits_df):
    """
    Calcula el nombre de partits guanyats, empatats i perduts per cada equip.

    Paràmetres:
        partits_df (DataFrame): Taula amb tots els partits, incloent la columna "Guanyador".

    Retorna:
        DataFrame: Taula amb columnes:
            - Equip
            - Guanyats
            - Empatats
            - Perduts
    """
    estadistiques = {}

    for _, fila in partits_df.iterrows():
        local = fila["Local"]
        visitant = fila["Visitant"]
        guanyador = fila["Guanyador"]

        # Inicialitzar equips si no existeixen
        for equip in (local, visitant):
            if equip not in estadistiques:
                estadistiques[equip] = {"Guanyats": 0, "Empatats": 0, "Perduts": 0}

        # Assignar resultats
        if guanyador == "empat":
            estadistiques[local]["Empatats"] += 1
            estadistiques[visitant]["Empatats"] += 1

        elif guanyador == local:
            estadistiques[local]["Guanyats"] += 1
            estadistiques[visitant]["Perduts"] += 1

        elif guanyador == visitant:
            estadistiques[visitant]["Guanyats"] += 1
            estadistiques[local]["Perduts"] += 1

    estadistiques_df = (
        pd.DataFrame.from_dict(estadistiques, orient="index")
        .reset_index()
        .rename(columns={"index": "Equip"})
    )

    return estadistiques_df



def construir_taula_final(estadistiques_df, gols_per_equip, gols_rebuts_per_equip, classificacio_df):
    """
    Construeix la taula final de classificació combinant:
        - estadístiques de partits (guanyats, empatats, perduts)
        - gols marcats
        - gols rebuts
        - punts totals

    Paràmetres:
        estadistiques_df (DataFrame)
        gols_per_equip (DataFrame)
        gols_rebuts_per_equip (DataFrame)
        classificacio_df (DataFrame)

    Retorna:
        DataFrame: Taula final ordenada per punts.
    """

    taula = (
        estadistiques_df
        .merge(gols_per_equip, on="Equip", how="left")
        .merge(gols_rebuts_per_equip, on="Equip", how="left")
        .merge(classificacio_df, on="Equip", how="left")
    )

    # Ordenar per punts
    taula = taula.sort_values("Punts", ascending=False).reset_index(drop=True)

    # Reordenar columnes
    taula = taula[
        ["Equip", "Guanyats", "Empatats", "Perduts",
         "Gols_x", "Gols_y", "Punts"]
    ]

    # Renombrar per claredat
    taula = taula.rename(columns={
        "Gols_x": "Gols a favor",
        "Gols_y": "Gols en contra"
    })

    return taula

In [138]:
def processar_partits(path):
    """
    Orquestra completa del processament de partits.

    Pipeline:
        1. Carregar i convertir el fitxer en DataFrame.
        2. Calcular gols marcats per equip i màxim golejador.
        3. Calcular gols rebuts per equip i equip més golejat.
        4. Calcular classificació (punts).
        5. Calcular estadístiques (guanyats, empatats, perduts).
        6. Construir taula final combinada.

    Paràmetres:
        path (str): Ruta del fitxer "historic_partits.txt".

    Retorna:
        dict: Diccionari amb totes les taules i resultats:
            - partits_df
            - gols_per_equip
            - maxim_golejador
            - gols_rebuts_per_equip
            - maxim_coladero
            - classificacio_df
            - estadistiques_df
            - taula_final
    """

    # 1. Carregar dades
    partits_df = carregar_partits(path)

    # 2. Gols marcats
    gols_per_equip, maxim_golejador = calcular_gols(partits_df)

    # 3. Gols rebuts
    gols_rebuts_per_equip, maxim_coladero = calcular_gols_rebuts(partits_df)

    # 4. Classificació
    classificacio_df = calcular_classificacio(partits_df)

    # 5. Estadístiques
    estadistiques_df = calcular_estadistiques(partits_df)

    # 6. Taula final
    taula_final = construir_taula_final(
        estadistiques_df,
        gols_per_equip,
        gols_rebuts_per_equip,
        classificacio_df
    )

    return {
        "partits_df": partits_df,
        "gols_per_equip": gols_per_equip,
        "maxim_golejador": maxim_golejador,
        "gols_rebuts_per_equip": gols_rebuts_per_equip,
        "maxim_coladero": maxim_coladero,
        "classificacio_df": classificacio_df,
        "estadistiques_df": estadistiques_df,
        "taula_final": taula_final
    }

In [144]:
def mostrar_resultats(resultats):
    """
    Mostra per pantalla tots els resultats del processament:
        - gols per equip
        - equip més golejador
        - equip més golejat
        - classificació
        - taula final completa
    """

    print("📊 TOTAL DE GOLS PER EQUIP")
    display(resultats["gols_per_equip"])
    print()

    print(f"🥇 Equip més golejador: {resultats['maxim_golejador'].iloc[0]}")
    print(f"   Gols marcats: {resultats['maxim_golejador'].iloc[1]}\n")

    print(f"🥅 Equip més golejat: {resultats['maxim_coladero'].iloc[0]}")
    print(f"   Gols rebuts: {resultats['maxim_coladero'].iloc[1]}\n")

    print("📈 CLASSIFICACIÓ FINAL")
    display(resultats["classificacio_df"])
    print()

    print("📘 TAULA COMPLETA DE CLASSIFICACIÓ")
    display(resultats["taula_final"])

In [ ]:
# --- EXECUCIÓ FINAL DEL PIPELINE ---

resultats = processar_partits("historic partits.txt")

mostrar_resultats(resultats)

📊 TOTAL DE GOLS PER EQUIP

                  Equip  Gols
0              Figueres   161
1            Llagostera   159
2            Vilafranca   157
3              Cornellà   147
4              Terrassa   147
5              Sabadell   141
6             Girona FC   139
7              Badalona   134
8                  Olot   132
9          RCD Espanyol   131
10  Nàstic de Tarragona   130
11      Lleida Esportiu   129
12         FC Barcelona   125
13          Sant Andreu   123
14           Granollers   122
15        Reus Deportiu   119
16           Cerdanyola   117
17              Manlleu   106
18                 Prat   106
19               Europa    93

🥇 Equip més golejador: Figueres
   Gols marcats: 161

🥅 Equip més golejat: Vilafranca
   Gols rebuts: 172

📈 CLASSIFICACIÓ FINAL

                  Equip  Punts
0             Girona FC     96
1            Llagostera     94
2              Sabadell     85
3              Cornellà     82
4          RCD Espanyol     80
5              Figueres     79
6       Lleida Esportiu     75
7              Terrassa     74
8          FC Barcelona     73
9            Vilafranca     72
10             Badalona     68
11  Nàstic de Tarragona     68
12        Reus Deportiu     68
13           Granollers     67
14                 Olot     64
15          Sant Andreu     62
16              Manlleu     57
17           Cerdanyola     56
18                 Prat     56
19               Europa     41

📘 TAULA COMPLETA DE CLASSIFICACIÓ

,Equip,Guanyats,Empatats,Perduts,Gols a favor,Gols en contra,Punts
0,Girona FC,31,3,13,139,94,96
1,Llagostera,29,7,20,159,142,94
2,Sabadell,26,7,15,141,121,85
3,Cornellà,25,7,22,147,146,82
4,RCD Espanyol,23,11,21,131,144,80
5,Figueres,23,10,23,161,154,79
6,Lleida Esportiu,23,6,23,129,133,75
7,Terrassa,20,14,23,147,164,74
8,FC Barcelona,22,7,15,125,115,73
9,Vilafranca,20,12,25,157,172,72
10,Badalona,18,14,16,134,124,68
11,Nàstic de Tarragona,20,8,27,130,148,68
12,Reus Deportiu,20,8,16,119,111,68
13,Granollers,21,4,24,122,117,67
14,Olot,18,10,26,132,144,64
15,Sant Andreu,17,11,25,123,134,62
16,Manlleu,16,9,18,106,118,57
17,Cerdanyola,17,5,28,117,133,56
18,Prat,16,8,21,106,111,56
19,Europa,12,5,16,93,93,41